### ISSUE TITLE
New Earpiece not Registered Correctly

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#102]
If the current user uses a new earpiece - while the audio works correctly, the new earpiece MAC address will register - but we need to make sure this does not disrupt any cross-references in the user friend, devices tables etc

**Comment by dakshatechnologies** [comment]
kindly explain cross_reference concept

**Comment by cjcornell** [comment]
I may be mistaken on this task ... but please verify:
- every time cyrano starts, it registers the MacAddr of the earpiece....
- even if the user has a different earpiece every time, the Identifying piece of information is the phone mac address? not earpiece.
- My confusion:  Cyrano is supposed to be using the user's earpiece BTID to detect other users ...  I want to make sure that if the user changes their earpiece, that it will not affect this detection.

There MAY be NO work required on this task!  But please clarify!

**Comment by dakshatechnologies** [comment]
definitely , it will cause issue . If user can change the ear peace then  the MAC address is also changed  and it cannot detect the USER FRIEND.

**Comment by cjcornell** [comment]
I am not sure ....  Isn't user friend table only with ids and not MAC
addresses ?

**Comment by dakshatechnologies** [comment]
I have also check the bug as per your last message if the MAC address is changed then the device is not found and trigger is not executed.

**Comment by cjcornell** [comment]
- Right - and this is what I don't understand.  (or maybe you don't understand my question)
- You see ... upon login, Cyrano registers the earpiece to the userid of the user logged in.  from then-on, any references to the user should be via their user_id, not via the earpice MAC address.
- For triggers ... this has nothing to do with the user's earpiece MAC address (or **should** have absolutely nothing to do with it)
- when Cyrano (or the simulator) detects a trigger MAC address, it should match it to the **devices** table - which associates the trigger with a user_id (owner) a unique device_id  (once we have the device_id, no Mac addresses are needed anymore)
- then Cyrano should match the user_id and device_id within the triggers_alarm table to see if there is a trigger.

- from you note, i cannot tell if you understand the problem
- when cyrano registers a new bluetooth earpiece for the current user 
   1. how can device MAC addresses be affected?
   2. the user_id does not change, so why would any other table relationships change?  (friends, triggers, locations)
   3. why would triggers be affected?
right now this does not work as expected, but your answer does not really help to clarify.

**Comment by cjcornell** [comment]
Seems to work OK for now ... we will see what happens in a week or two when we get back to non-simulated tests  (ie ... real devices).  Thanks.
