### ISSUE TITLE
Mute/Snooze All - Icon Refresh

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#11]
Bug/Issue Report
Based on Build Tested:
Cyrano_05_13_2015_01.apk
(latest build available, at the time of testing)

Icons in Nearby Friends list (next to each name in the list) are not updated or refreshed when MuteAll or SnoozeAll are chosen.

Upon tapping MuteAll or SnoozeAll the each of the the nearby friends in the list should be internally marked for mute or snooze, and, on the display, should have the appropriate status icon (for mute or snooze) displayed.

**Comment by cjcornell** [comment]
Still issues.  as of build: Cyrano_05_15_2015_04.apk

While I can set the mute/snooze ..
If II UNSnooze all .. then try to Snooze all again ... the last "mins" I chose appears, and it looks like I am snoozing, but nothing happens.  The UI is unclear.   But worse, the functionality does not work as expected.

This also happens when navigate elsewhere in Cyrano and return to the Nearby friends screen and try to UNSnooze.

Please test, and fix.

**Comment by kevinlee85** [comment]
Already fix with the last released version.

**Comment by cjcornell** [comment]
not fixed.
Mute-all  does not change icons for all.

**Comment by kevinlee85** [comment]
Hi CJ:
You need to wait 2 seconds because it a syn tasks to update it.
