### ISSUE TITLE
Login via Facebook is different than via email/pswd

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#14]
CJ Cornell (id=100  cjcornell@cjcornell.com) has one user record. 
It is also registered with facebook - but I also have an email/password combo. 
Logging in with one or the other gives much different results - esp for the Account screen.
Different photo and name

**Comment by dakshatechnologies** [comment]
I have check you app code completely and fix the issue actually the problem was in REST call. please check your app now account picture is show correctly.

**Comment by cjcornell** [comment]
You are not understanding the entire issue ...
- There is one record (in user table) for me, cjcornell  
- I can log in via cjcornell@cjcornell.com or via facebook 
- either one SHOULD still be the same user record for me  (id=100)
- but if I login with the cjcornell@cjcornell.com / cjcornell  combination, my user record "account" screen shows someone else's photo.
- if I login with facebook, then the photo associated with my account is ok.

**Comment by dakshatechnologies** [comment]
Its almost resolved you can check when i,ll send you new build
