### ISSUE TITLE
Location Features - Issues Pending?

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#16]
Tested build 
Cyrano_05_13_2013_03  and  Cyrano_05_15_2015_04.apk

My User Location  (User 100) = 
33.684185	-111.9903541

The last 2 should be detected as locations at least  (and announce, display in a list, and trigger a scriipt).   They are not showing at all....
Not sure if it is a bug or the test... or both

Look in Locations
id	user_id	location_id	GPS_latitude	GPS_longitude	distance_range	location_type	
1	206	1	30.718681	76.7055	2	PLACE	work place	
2	207	2	31.2027555	75.8603609	2	demo	demo	
3	100	3	200	200	50	Test 1	Just the Test 1	Here is the description for test 
4	100	4	33	-111	3	Applia	Refrigerator	A test of a refrigerator close 
5	100	5	40	-110	11	Car	My Jeep	Test of my jeep - 11 feet away.

**Comment by dakshatechnologies** [comment]
cj you enter the wrong co_ordinates in GPS_latitude and GPS_longitude in locations table.

please check .

**Comment by dakshatechnologies** [comment]
.

**Comment by cjcornell** [comment]
Thank you.  It is looking OK ...

I still need to test some features, that might overlap with the Polling Enhancements milestone.

But please let me know which of these should work right now:

1. announcements of # locations
2. TTS of specific location (about)
3. mute/snooze of locations
4. script execution (triggers) based on location

Thanks..

**Comment by cjcornell** [comment]
Take a look at my questions:


please let me know which of these should work right now:

1. announcements of # locations
2. TTS of specific location (about)
3. mute/snooze of locations
4. script execution (triggers) based on location
