### ISSUE TITLE
Audio Features

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#19]
Testing Cyrano_05_15_2015_04.apk

Please advise what I am supposed to be seeing/hearing... and/or how to test.

I am using the baseline test account (cjcornell@cjcornell.com) and nothing seems to be confiigured to demonstrate the new audio features.

**Comment by avaiyakirtib** [comment]
Hi,
You may want to check the Pretone before Triggering alarm,script voice and friend found.
you may also want to check Vibrate level and volume level while voice is playing in the cyrano.
you may found it in the latest apk which already on FTP .

**Comment by cjcornell** [comment]
Give me something got test.   How a YOU testing this ?  Are you actually testing with the baseline test account?

**Comment by avaiyakirtib** [comment]
yes I am testing with the baseline test account cjcornell@cjcornell.com ,cjcornell password
i am not getting that why you need special testing account or expecting. because I have tested with only above account at my development stage

**Comment by cjcornell** [comment]
Ok.... So I run cyrano ... I hear nothing new with audio ....

**Comment by avaiyakirtib** [comment]
ok Let me ask you something
are you getting friends near by ?

**Comment by cjcornell** [comment]
Yes.

**Comment by avaiyakirtib** [comment]
ok so are you not able to here any sound or vibrate just before friend announcement ?

**Comment by cjcornell** [comment]
No.

**Comment by avaiyakirtib** [comment]
ok I don't know why its not playing at your end,Let me check again at my end.

**Comment by avaiyakirtib** [comment]
Hi, I am able to hear voice like "Tik" voice same as "beep"

**Comment by avaiyakirtib** [comment]
and yes its now depends upon database value so are you trying with 0 ? if yes then it might be you can not able to hear pre_tone.

**Comment by cjcornell** [comment]
I am not changing any settings, sir.   We are using the same user profile settings.

**Comment by avaiyakirtib** [comment]
Yes, Let me check the apk again you are trying from FTP

**Comment by avaiyakirtib** [comment]
yes you are right, It seems problem in apk, Let me give you another build on FTP

**Comment by avaiyakirtib** [comment]
please check now on FTP with file name Cyrano_05_15_2015_05.apk and Cyrano.apk

**Comment by cjcornell** [comment]
OK -- I felt vibration during certain times.
But I will test the new version ... going into meetings right now - but will try to test and reply in a few hours.

**Comment by avaiyakirtib** [comment]
ok I am signing off from here , Please share your feedback so that I can check.

**Comment by cjcornell** [comment]
tested ...
still not hearing it ..
perhaps it is too high pitched for me to hear?  perhaps the "tone" is not installed on my device?

**Comment by avaiyakirtib** [comment]
Hi
I have checked again the apk and its working fine,May be you need to check below things in your device
- It may due to your volume of device may down
- It may due to your phone is on silent mode or airplane mode.

**Comment by cjcornell** [comment]
this does not make sense, Kirti ...   if I had the phone in silent mode or volume down, then I would not be able to hear the "nearby friends" announcements or script audio.
