### ISSUE TITLE
Snooze - Mute (Clarifications)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#22]
OK - I am going to try to make this simpler.  Even though this is a LONG writeup, the resulting actions required are simple and straight forward. I am trying to format it so it is an easy-read, and follow, so we can finally close this issue!

There are 2 over-arching issues regarding Snooze and Mute
1. Internal - Making sure that the settings and status are working and accurate.
2. UI - Making sure the "buttons" are intuitive and that the correct mute/snooze status is displayed accurately.

Without discussing what is 'wrong' with the current implementation, here is a discussion of how it should work.  Some of this is a little 'new' because I have modified the requirements in order to simplify, since it has been several weeks of confusion in getting it right.

Starting with the UI

**MUTE/SNOOZE UI is relevant in 2 areas of the app:**
1. In the detail-view of any individual nearby friend.
2. In the List of Nearby Friends

**Operation**
_1. Nearby Friend Detail-View_
Current Mute/Snooze Status
    * Somewhere prominently on the screen, should be the status.  
    * Is the Friend Muted?  Snoozed?
    * If Snoozed, how much time is left until Snooze has expired.
* Buttons to Toggle Mute and Snooze
    * Mute/UnMute button:
         * If Friend is currently Muted (internally) then this button appears as "UNMute"
         * Otherwise this button appears as MUTE

         * If MUTE Pressed, then 
          1. Internally, Mute status is set.
          2.  Mute Status is reflected on this screen
          3. The Button changes to UNMUTE

         * If UNMute Pressed, then
          1. Internally, the Friend's mute status (and snooze status) is cleared
          2. on screen mute/snooze status is cleared,  (no status needs to display)
          3.The Button changes to MUTE

    * Snooze/UnSnooze button:
         * (please note that this description is a CHANGE from the current implementation - a simplification - the 'dropdown' of snooze time choices will no longer be used)
         * If Friend is currently Snoozed (internally) then this button appears as "UNSnooze"
         * Otherwise this button appears as SNOOZE
         * If SNOOZE is Pressed, then 
         a. Internally, SNOOZE status is set with a Snooze-Time Increment EQUAL to an Internal Field/Value  (See Milestone/spec for New Polling Rules).  ie.  No more dropdown for choosing the snooze duration.  It is always set to an internal value (that comes from user settings for a default snooze value)
         b. Snooze Status is reflected on this screen  (e.g. Snoozed: 15:00 mins remaining)
         c. The Button changes to UNSNOOZE

         * If UNSNOOZE Pressed, then
         a. Internally, the Friend's Snooze status (and mute status) is cleared
         b. on screen mute/snooze status is cleared,  (no status needs to display)
         c. The Button changes to SNOOZE

__2. Nearby Friend LIST__
Current Mute/Snooze Status
* Next to each user name in the list may be an icon:
   * If the user is "muted" then a special "mute" icon displays right justified on the same line as the user.
   * If the user is "snoozed" then a special "snooze" icon displays right justified on the same line as the user.
   * If the user is neither "muted" or "snoozed"  then no icon is displayed right justified on the same line as the user.

Buttons on bottom of screen
* MUTE  UNMUTE and  SNOOZE UNSNOOZE:  These should be 4 buttons (2 pair).  Always active.

    a. if MUTE is Pressed, then internally, all users in the list are set to "mute" and the list is refreshed to reflect the icons. note - this will clear any snooze timing for each user.
      - Mute Status is reflected on this screen  (e.g. ALL Muted) as a temporary message that disappears after a few seconds.

    b. if UNMUTE is Pressed, then internally, all users in the list have their mute/snooze parameter cleared. and the list is refreshed to reflect the cleared icons. 

    c. if SNOOZE is Pressed, then internally, all users in the list are set to "mute" and the list is refreshed to reflect the icons. note - this will clear any snooze timing for each user.
       - Internally, SNOOZE status is set with a Snooze-Time Increment EQUAL to an Internal Field/Value  (See Milestone/spec for New Polling Rules).  

      - ie.  No more dropdown for choosing the snooze duration.  It is always set to an internal value (that comes from user settings for a default snooze value)

      - Snooze Status is reflected on this screen  (e.g. ALL Snoozed: 15:00 mins remaining) as a temporary message that disappears after a few seconds.
   d. if UNSNOOZE is Pressed, then internally, all users in the list have their mute/snooze parameter cleared. and the list is refreshed to reflect the cleared icons.

**Comment by kevinlee85** [comment]
Hi Cj:
I have a question about the different between MUTE and SNOOZE.
By my understanding, MUTE means no voice will be trigger on this user.
SNOOZE means no voice will be trigger on this user with a time remaining.
Am i right?

**Comment by cjcornell** [comment]
@kevinlee85  - 
Sort of ... Mute/Snooze are not really "audio" mute ... but more "detection" muting...
Here are some clarifications

MUTE = Ignore
--------------------------
MUTE will cause the polling routine to SKIP a detected ID for a User (or device, or location) - so it will not process anything associated with it (annoucements, triggers, others)
UNTIL either 
- Cyrano is restarted
- The device is out of range and then later comes back into range
- the user changes the mute/snooze status.

SNOOZE = Ignore for a fixed time period.
------------------------------------------
Same as MUTE, above, except there is an end-time associated with the device-ID.

NOTES
-------------
The processing for all this is really handled in the polling routine, and in the "prior-state" file  (ask @dakshatechnologies  for details).   But for your purposes you don't need to know all the details.

FOR THIS Task - and the revised clarifications ....
while they seem lengthy - they are really simplified to 
4 buttons  [MUTE][UNMUTE]   [SNOOZE][UNSNOOZE]
(affecting all IDs in the list)

**Comment by kevinlee85** [comment]
Hi CJ:
Thank your very clearly explanation.
The 4 buttons's UI process almost no problem, just need to remove the time selection nearby the snooze button.
I want to know the details is about the logitech parts, i think even after i marked the status as snooze, and it not really snoozed, just updated the UI.
I can help to test and verify if i know what's the correct expectation manipulations.

**Comment by kevinlee85** [comment]
Fixed by "Cyrano_05_21_2015_01.apk"
