### ISSUE TITLE
Friend - user_about/persnal reminder  - no longer playing

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#24]
A new bug.

Now, when the detail screen for a Friend is viewed it no longer plays the details about that user (personal reminder).

This is a bug that just re-appeared in the current release.

**Comment by dakshatechnologies** [comment]
personal reminder announce correctly i have check and also check when i tab on friends details

**Comment by cjcornell** [comment]
I tested all morning ...  not working.
current build is broken, waiting for a new build, then I will test again, but this feature has not worked, in a few days.

**Comment by dakshatechnologies** [comment]
i have test this feature and this is work
