### ISSUE TITLE
Bug - Simulation Not processing "SCAN" Properly

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#25]
New bug in the most recent releases.

Simulation file (pasted below) should only play a specific script-trigger ONCE upon encountering SCAN 3  (the third scan).  Instead - it appears to be playing during EVERY SCAN/Poll.

--------------------
On
// XX:01:01:04:04:01               // does not exist as a device or friend or user
XX:01:01:01:01:01		// Steve Jobs
XX:03:03:03:03:01               // Hillary CLinton  (not a cjcornell friend)
XX:02:02:02:02:01           	// Barack Obama
XX:04:04:04:04:01 GLOBAL    	// Bill Clinton (not a cjcornell friend)

SCAN 3 START 		   // This scan will execute on 5th poll
YY:01:01:04:04:01          // a CJ Device
YY:01:01:01:01:01  		// Trigger - Device owned NOT  cjcornell (refigerator script) 
4C:BC:A5:34:A0:81            //  a device - not my device  should not execute
//hello
E8:92:A4:EF:A9:46            //  a device - not my device  should not execute
//ok
31:D5:6C:E4:ff:ff
// special beacon list
SCAN 3 END
//  aa:bb:cc:dd:ee:ff
SCAN   START        		
   // XX:xx:xx:xx:xx:xx GLOBAL     // Demo to start block  
SCAN   END

**Comment by dakshatechnologies** [comment]
The trigger can play again and again or execute as per your wording because of that the trigger can find along with location . other hand i mean every time trigger was found with location it can play again and again

**Comment by cjcornell** [comment]
oh - you have location enabled, for triggered-devices?
(and the coordinates match my location?)

**Comment by dakshatechnologies** [comment]
which location you found on every poll that location has a script id check on location table and script is execute every poll when location is found

**Comment by cjcornell** [comment]
is that a question?

**Comment by cjcornell** [comment]
you need to tell me.  if something new is happening.
right now, by looking at the simulation file
only one trigger/script should play, when Scan #3 is done.
but right now, a trigger plays several times.

**Comment by dakshatechnologies** [comment]
no this is explanation of trigger execution on every poll

**Comment by dakshatechnologies** [comment]
"you need to tell me. if something new is happening.
right now, by looking at the simulation file
only one trigger/script should play, when Scan #3 is done.
but right now, a trigger plays several times."
which trigger is plays several time this is the trigger which is found with location

**Comment by cjcornell** [comment]
i am having trouble understanding your english.

**Comment by dakshatechnologies** [comment]
the trigger that run with several time its is nor simulation file trigger
