### ISSUE TITLE
Triggers - Improperly Playing Script Commands

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#26]
When a trigger references a script command to play, the key field is script_id + command_id
(both)

If there is no match, then no script command record should execute

most times right now - the trigger references a correct script command_id - but not the correct script_id.   and the trigger plays the command_id record.  this is incorrect.

**Comment by dakshatechnologies** [comment]
kindly let me know the above wording or message are related to which problem ? please explain in brief.

**Comment by cjcornell** [comment]
I thought this was pretty clear.
right now  (incorrectly) it seem that when Cyrano encounters a trigger_alarm record, it only uses trigger_alarm->command_id to match to a record in script_commands->command_id

instead, we need to match trigger_alarm->script_id+trigger_alarm->command_id  to   script_command->script_id+script_command->command_id 

understand

**Comment by cjcornell** [comment]
Still happemming

**Comment by cjcornell** [comment]
Rules for Triggers:

- If there is a script_id and command_id - then the trigger will play the script_id STARTING from script_id+command_id

- if there is a script_id and no command_id - then the trigger will play the entire script from the first command_id record

- if there is a command_id and no script_id  - then the trigger will play the command_id record ONLY.

**Comment by cjcornell** [comment]
This needs attention.  Script Trigger programmed in simulation not executing script at correct record ...

**Comment by cjcornell** [comment]
Additional info

I tested 

YY:01:01:04:04:01          // a CJ Device   - DID 205, This Triggers Script 44 Command 14
                           //  this trigger should play a record from BASELINE script "Press ONE"

This does not work properly ... nothing triggers.

**Comment by dakshatechnologies** [comment]
you want to trigger is only execute command no 14?

**Comment by cjcornell** [comment]
Rajesh - you did not read the other comments completely, so I will paste here again:

Rules for Triggers:
1. If there is a script_id and command_id - then the trigger will play the script_id STARTING from script_id+command_id
2. if there is a script_id and no command_id (blank) - then the trigger will play the entire script from the first command_id record.
3. if there is a command_id and no script_id (blank) - then the trigger will play the command_id record ONLY.

*Additional info*

I tested a simulation file with this line:

YY:01:01:04:04:01 // a CJ Device - DID 205, This Triggers Script 44 Command 14
// this trigger should play a record from BASELINE script "Press ONE"

This does not work properly ... nothing triggers.  
- as per the original spec'd rules, the above should play the Baseline script Starting from command_id=14   (and continue playing).
- but IF (as an example) that simulation device trigger record contained a blank script_id then it should ONLY play command_id 14

Understand?

**Comment by dakshatechnologies** [comment]
Cj i really feel so happy to work with you but if you don,t mind you are never discuss about trigger rule in  any past milestone .
