### ISSUE TITLE
Cyrano UI Unresponsive During Script Audio

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#27]
This is a new bug  (in the past few releases).  It appears to be consistent.
When a script is playing/executing - whether as part of a triggered script, or a script that was started via the script menu:   When the script plays, often, the script-control buttons, or the options menu UI simply freeze or are unresponsive.  

It appears this happens during the "command duration" period - but I am not sure.
It could be that this has something to do with a polling conflict.

Please test,, duplicate and fix.

**Comment by cjcornell** [comment]
Cyrano appears unresponsive during different times polling loop.   often i cannot press the back key to get out of Nearby friends, and then after 15 secs or so, the system responds.

**Comment by cjcornell** [comment]
This bug is consistent - script buttons unresponsive while playing audio (actually it seems like happens during the entire duration).   This seems to have started as a result of the Fix-request,  that was completed by @Atteq  for "cancel button does not cancel script from playing""

**Comment by dakshatechnologies** [comment]
i have fixed this issue And you will never face  this problem again
