### ISSUE TITLE
Script Audio Not playing Anymore!

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#3]
As a result of the last 2-3 builds (not sure when it began) - but now - playing scripts no longer plays the Text to Speech (TTS) audio.   

This bug also applies to scripts triggered as well, not surprisingly.

While I assigned this to @dakshatechnologies   because there is only one person at a time to assign... it also concerns  @avaiyakirtib  too ...   I am not sure where the problem originated but it must be solved ASAP.

**Comment by dakshatechnologies** [comment]
By mistake you had switch off the audio of app unless everything is working well

**Comment by cjcornell** [comment]
>> By mistake you had switch off the audio of app unless everything is working well  
@dakshatechnologies  
@Atteq 
@avaiyakirtib 
it is working now 
since I have not downloaded a new build - I assume the issue was REST related (and/or related to a setting in the database.
but I need to understand WHY this was not working earlier.

**Comment by dakshatechnologies** [comment]
i have fix this this issue. if audio is off in settings then scripts can advance automatically according to their time delay

**Comment by avaiyakirtib** [comment]
Hi Guys,Please let me know If I need to check anything at my end

**Comment by cjcornell** [comment]
While this issue seems to be solved - I really want to know WHY it occurred.
whether it was due to old code re-appearing due to faulty merging, or due to some internal settings or anything else i was not aware of.

This is not about blame at all .. I just want understand why this bug occurred by surprise.

**Comment by dakshatechnologies** [comment]
Cj there is a old code in app for Advancing Script .But the code not actually coded for when Audio is off in app settings the scripts can Advancing automatically.So i fix that part write a small part of code when 
Audio off in app setting then script can Advancing automatically according to it Time Delay

**Comment by cjcornell** [comment]
OK - but what do you mean by "old code"? 

And thanks for fixing it.

**Comment by dakshatechnologies** [comment]
old code means already coded before to assigning the the app us
