### ISSUE TITLE
Location Test - Bugs

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#33]
I "disabled" all locations - by making sure every coordinate in the locations table did NOT match my current location.  

and yet

Cyrano is announcing locations
and 
Playing Triggers

My location is
33.68416729	-111.99046447	

I coded all locations as

32	110	85
33.6840972	111.99038835	10
200	200	50	
33	300	3	
40	-110	11	
33.6841375	111.9904658	12796

**Comment by cjcornell** [comment]
READ THIS BUG REPORT@

**Comment by dakshatechnologies** [comment]
33.6841375 111.9904658  range 12796

this location is under your coordinate range thats by cyrano announce location name demo

**Comment by cjcornell** [comment]
@dakshatechnologies 
Thank you.
I will close this bug but ---two things
1. this entry is new so I never saw it 
2. this entry should not show up as a location for the cjcornell user because it is not "owned" by me.

I am not going to ask you to fix this, but will log it for a later change since we have to address "ownership" issues elsewhere too.

Thanks.
