### ISSUE TITLE
Nearby Friends - Does not announce properly

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#34]
Cyrano announces  (on first announcement)
"there are 3 friends nearby"
and then says something short (cannot figure out ... sounds like "demo")
but annouces name of the friend(s) or personal_reminders

part of this may be due to internal polling flag settings but not the names-announcement bug.

**Comment by dakshatechnologies** [comment]
the "demo" is announce that indicate the location name

**Comment by cjcornell** [comment]
TEST this ,,
it is announcing demo - for nearby friends
the system NO LONGER announces the names of the friends (on the first poll) along with their personal reminders.
there is something not working correctly

**Comment by dakshatechnologies** [comment]
Cj the demo is location name and when first poll is starts it will announce that time location name and execute location trigger and then the friend detection value is increasing  and it will be mark as snooze and not announce the name of the friends

**Comment by cjcornell** [comment]
Th  location should never announce.  I changed the coordinates so for is far far away from th  user coordinates.

**Comment by dakshatechnologies** [comment]
name and personal reminder is not announce because same time the location name announce

**Comment by cjcornell** [comment]
I checked.  I disabled the extra location (see issue #33 ) ... and
the Nearby Friends announcements are still not exactly correct.
I am not sure this is due to the internal polling variables or if it is a bug::

For any Friend (or location) that is NEWLY found  (ie - the BTID was not in the prior-state file) - then Cyrano should announce both the name and the personal_reminders (details).  
Unless the following polling flags are set ..Magicm0702

- details_1_frequency ### - announce first level details (ie. users->about_announce - every ### announce_frequency)  default = 
- details_2_frequency ### - announce second level details (ie user_friends->personal_reminder announcement) every ### announce_frequency.
- auto_mute_1 ### automatically mute first level details (ie users->about_announce  announcement) after ### announce_frequency.
- auto_mute_2 ### automatically mute second level details (ie user_friends->personal_reminder announcement) after ### announce_frequency.
- trigger_mute ### automatically suspend triggers after ### announce_frequency. default = 0 (no muting)


SO - I still do not know if this is a bug or if the internal polling flags are functional, and the internal values are the cause ....

**Comment by cjcornell** [comment]
OK....
I am closing this for now ...
