### ISSUE TITLE
Simulation SCAN ## START - not working?

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#36]
This block below
has a device in it that should trigger  (the first one)
It never triggers.
but when I put the same code outside of the SCAN ... START block, the trigger works

SCAN 3 START 		   // This scan will execute on 3rd poll
YY:01:01:04:04:01          // a CJ Device   - DID 205, This Triggers Script 44 Command 14
                           //  this trigger should play a record from BASELINE script "Press ONE"
                           
YY:01:01:01:01:01  		// Trigger - Device owned by 101 NOT  cjcornell (refigerator DID  201, 58/53
4C:BC:A5:34:A0:81            //  a device - not my device  should not execute  UID 30, DID 6, No trigger
//hello
E8:92:A4:EF:A9:46            //  a device - not my device  should not execute  UID 26, DID 3  No trigger
//ok
31:D5:6C:E4:ff:ff            // UNKNOWN - Unregistered Device no trigger, no script etc
// special beacon list
SCAN 3 END

**Comment by cjcornell** [comment]
@dakshatechnologies 
I reported this as a bug yesterday - but unfortunately assigned it incorrectly until now.

**Comment by cjcornell** [comment]
This is consistent

**Comment by dakshatechnologies** [comment]
hello cj i have fix this problem
