### ISSUE TITLE
Location Detect - Owners Only

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#38]
Locations not matching the User_Id of the current user are not to be shown as "nearby" (even if in range)

Later we will have rules about sharing locations, triggers and scripts - but not now.  If there is an "owner" User_ID for a record (location, trigger, friend ... others) then it must match the current user's User_ID

**Comment by dakshatechnologies** [comment]
Fix if the current user_ id record exist in location table then query not matched this record and not shown in nearby location please check

**Comment by cjcornell** [comment]
Not fixed.  No change in behavior.  I am running build:  Cyrano_05_26_2015_09.apk   - so check to see that your changes were merged

**Comment by dakshatechnologies** [comment]
the location system is works like .it is only matches the records in location table which is user is not equal to the current user id and if the any record is under range of which specify then it is display on near by location

**Comment by cjcornell** [comment]
Please don't insist that something works correctly.  That is my job to decide.  
and - your description is incorrect.
(right now) - only locations matching the user_id of the current user_id should announced (if in range).  You have it backwards.

**Comment by dakshatechnologies** [comment]
I have done this as per your requirement. Please check it
