### ISSUE TITLE
Pre-Tones

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#40]
Pre-tone flags (in User Settings) do not seem to have an effect  (User ID = 100 is the baseline test account we use)

Cannot specify the pretone style used.

**Comment by avaiyakirtib** [comment]
Hi,
It might be issue because we did not implement table to manage all the things for pre_tone style

**Comment by cjcornell** [comment]
from my Slack message:

to complete this, here's what I suggest
1. upon user login, download all the tone files   (I will remove most of them)
(it has to be done upon login before processing  - definitely not downloaded on-demand)
2. I will rename the files   1-<filename>   2-<filename> etc ....
the first character representing the Tone #
3. modify the tone routine to use the filename with the first (numeric) character matching the tone_number parameter

this way, the user_setting for whether pretones are enabled and the pretone number, can be user (for the current user).

Finisihing this should be quick now.  If it seems difficult, then let me know because it probably means you are over-thinking the above suggestion.  Thanks

**Comment by cjcornell** [comment]
In testing - I have heard different tones  (not sure what I am hearing more than 1 different right now) but NONE of the tones I am hearing is one of the 6  pretone files I have supplied (filename begginning with 1-  2- 3- ...)
and I have specified, in my user_settings that pre_tone_style=3
