### ISSUE TITLE
Error During Friend Search

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#41]
Intermittent "Getting Error During Friend Search"
Why?

But even more important  - getting this message seems to interfere with the SIMULATED friends in the simulation file.....

**Comment by dakshatechnologies** [comment]
this error occurs because error occurs when simulation file is read by cyrano. but now this is fix

**Comment by cjcornell** [comment]
OK - I will check.

**Comment by cjcornell** [comment]
Closing for now.  Will watch and re-open if it occurs again.
Thanks
