### ISSUE TITLE
Critical Bug in Simulation File Processing

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#42]
This one took me HOURS to find.

In Simulation file - I was trying to debug why SCAN 3  .... was not working
so I decided to add a nearby friend BTD here.
(under SCAN 3)
A0:B4:A5:B4:18:47          // CJ Friend Bhupinder Rana - should announce!

when i tested - NOTHING POLLED ....
errors

so, i commented it out

// A0:B4:A5:B4:18:47          // CJ Friend Bhupinder Rana - should announce!

STILL POLLING ERRORS ... no friends announced etc.

**Comment by avaiyakirtib** [comment]
Hi,
I have checked and I think its not implementation from my side so I think you should raise it to other people from team.

**Comment by cjcornell** [comment]
My mistake!   I was in a rush and assigned this to the wrong person. Sorry.  Thanks for letting me know

**Comment by dakshatechnologies** [comment]
it is worked correctly

**Comment by cjcornell** [comment]
"it is worked correctly" ...

I reported a BUG.   
And I spent 2-3 hours of hell trying to find out where this bug was.  IF you could not reproduce it, then state this.  If is very poor form merely to post "it worked correctly"  without any other comments.
