### ISSUE TITLE
Nearby Friends - Shows all

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#43]
NEW BUG

In the latest simulation file - I specify 4 friends....
(see 
- user_friends table to see that user 100 has exactly 4 friends ...
- and that the similation file    (copy at simulation-05-27-15-01.txt)  has those 4 friends in the initial scan.

When Cyrano Runs ...

1. After a unusually long initial waiting period ...
2. Cyrano announces, "there are 4 friends nearby"  (this is correct!)
3. Cyrano DOES NOT announce any of the personal details for these 4 friends 
Thsi
3.  But when I go to the LIST of nearby friends - I see a list of 6  !!  
there should be only 4 friends listed
so this leads me to believe that there are 2 issues
- that Cyrano, for some reason, now wants to list ALL the friends in the list
- that Cyrano UI - does not "scroll" (or page) as per spec - because I believe the the above bug is really wanting to display 7 items, but the UI design  of the list does not page/scroll to allow us to see other friends.

**Comment by dakshatechnologies** [comment]
this error was occur because the 5th and 6th friends has same BTmac address .that's by it is fetch the record of other two friends. but this issue is resolved and. you set the cyrano settings MAX friends is 3 that's by it is not announce the personal reminder of fourth friend.

**Comment by cjcornell** [comment]
Thank you (I did not check for duplicate BTIDs) ...      Max friends settings had nothing to do with it  (I was setting to max 3 and max 4 to test)
