### ISSUE TITLE
Cyrano Crash - Location/Trigger w Invalid Script ID

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#46]
Cyrano crashes "Unfortunately, Cyrano has stopped" ...  seems during a location announcement.
After much testing, I see the issue.
If the script_id / command_id destination does not exist - then cyrano crashes.
an extra line of error checking (probably in the REST code) should be added - to tell Cyrano not to execute a trigger.

**Comment by dakshatechnologies** [comment]
i have fix this
