### ISSUE TITLE
Nearby Friends <> Location Annoucements

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#49]
When testing Cyrano with an active location AND Script trigger  ...

if I tap a cancel button (in the script) - it appears that this might affect the Nearby Friend Detection!

there is no announcement (OR DETECTION) of nearby friends.  Friends do not even appear in the list.

Actually - with more testing there seem to be a lot of conflicts still existing when there is even 1 location matching (even if it does not trigger a script) - Nearby Friend detection simply does not happen.

**Comment by dakshatechnologies** [comment]
The cancel Button task in not done by me i think it can  be done by other team member. Either its not assigned me and neither its included in assigned milestone.

**Comment by cjcornell** [comment]
I did not think this was due to the cancel button (the cancel button operation existed long before you started here).  To me, this was about the polling.  But I will keep testing - the problem just might be the very unpredictable polling problems I reported earlier.
