### ISSUE TITLE
Pre-Tones need to play before any announcements

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#50]
if Pretone flag is ON (and there is a tone style specified)
then Cyrano should play a pretone before
1. announcement of Nearby Friends
2. announcement of Nearby Locations
3. announcement of Nearby Device
4. At the start of any Script Trigger (usually as a result of a Nearby Location or Device)

Right now, tones appear only to work before the firsst condition

**Comment by avaiyakirtib** [comment]
It will play different tones ,It might be you may listen same tones on different alerts as we are having 6 tones but I am not sure for this, Let me check and update you.

**Comment by cjcornell** [comment]
Oh playing different tones (for different kinds of announcements) is beyond spec right now  - but playing the selected pre_tone before these announcements is a priority.
I am not hearing them ...
right now testing 
Nearby Friends (this is working, but still testing)
Locations (dont hear it)
Script/Trigger (dont hear it)

**Comment by avaiyakirtib** [comment]
ok Let me check , you can share your feedback after more testing

**Comment by avaiyakirtib** [comment]
I have checked and it is working as below paradigm 
1 working in Friend(s) found
2 working in device(s) found
3 working in trigger(s) found
4 working in script announcement
5 Did not implemented for location as it is not spec before
