### ISSUE TITLE
Incorrect Pre-Tones playing, playing at incorrect time.

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#52]
Tested the latest build
(in addition to any other pretone bug reported)

Here is what is happening

right BEFORE  "nearby friends" announces
a pretone plays - but it is not the pretone selected.  nor is this pretone in the list of pretones.
right AFTER "nearby friends" announces
the correct pretone plays  (but the needs to play beforehand)

Then after nearby friends announces perhaps 3 times (3 polls) - the pretone no nolonger seems to play at all.  then it played correctly on the 4th announcement.  something inconsistent here.  still  ttesting

**Comment by cjcornell** [comment]
Verified and clarifying the second part of this bug ...
which is that pretones do not play when there are "4 friends" nearby ... but does play when there re "3 friends" nearby.

this is not as strange as it may sound - because the difference is that 3 friends a user setting "Friends to Announce" 
but this should have nothing to do with pretones.
this setting (correcctly working) says
"do not announce *details* (names) , if the number of friends exceeds this setting-value.
Cyrano still announces "There are nn Friend Nearby"

but pretones do not work for this!

**Comment by avaiyakirtib** [comment]
Comment for first issue:

a pretone plays - but it is not the pretone selected. nor is this pretone in the list of pretones.
[First need to table implementation for tone selection.]

Then after nearby friends announces perhaps 3 times (3 polls) - the pretone no nolonger seems to play at all. then it played correctly on the 4th announcement. something inconsistent here. still ttesting
[It might be because continuously searching for different alarm(pre tone) like device, trigger, friends etc..]

**Comment by avaiyakirtib** [comment]
Comment for second issue:

I have checked and pre tone always works either 3 friends found or 4 friends founds or no friends found.

**Comment by cjcornell** [comment]
No this does not work.

Here is what is happening

- right BEFORE "nearby friends" announces
    - a pretone plays - but it is not the pretone selected. nor is this pretone in the list of pretones.
- right AFTER "nearby friends" announces
   - the correct pretone plays (but this needs to play beforehand)

Tested and verified as a bug in the latest build.  5/29/2015

**Comment by cjcornell** [comment]
Also verified....
- Pretones work INcorrectly if announcement of 2 friends nearby  (incorrect thunder tone before, incorrect other tone, after)
- Pretones work INcorrectly (on Scan 3) - for 3 friends nearby... this time it plays a different incorrect pretone and then the same (incorrect) one afterwards.

This is just amazing how you dont see this.
