### ISSUE TITLE
Simulation problems - Lots of testing, Intermittent bugs

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#55]
So many polling issues (with the simulator) that I don't know where to begin,
It is apparent that these issues have been causing hours with of testing problems for many many weeks.
Most likely these are not new bugs, just that we thought there we other bugs - that were caused by these bugs, all along
This testing is only with Friends and Triggers .... I turned off any locations  for this set of tests.

Below are a series of simple simulation "scripts" (or commands) that I used for simulation files, along with the report on the behavior.

[simulation-TEST-1-WORKS.txt](http://cyrano.cjcornell.com/simulation-TEST-1-WORKS.txt)
[simulation-TEST-2-PROBLEMS.txt](http://cyrano.cjcornell.com/simulation-TEST-2-PROBLEMS.txt)
[simulation-TEST-3a-WORKED.txt](http://cyrano.cjcornell.com/simulation-TEST-3a-WORKED.txt)
[simulation-TEST-3b-PROBLEMS.txt](http://cyrano.cjcornell.com/simulation-TEST-3b-PROBLEMS.txt)
[simulation-TEST-4-PROBLEMS.txt](http://cyrano.cjcornell.com/simulation-TEST-4-PROBLEMS.txt)

**Comment by dakshatechnologies** [comment]
CJ

SIMULATION-TEST 2:-the simulation works correctly but the main problem is caused due to polling conflict.Now it is resolved

**Comment by cjcornell** [comment]
Closing for now.  Will re-document as I go through another round of testing.
