### ISSUE TITLE
Friend Detected - Not owned (not a friend)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#58]
in the simulation - I am  user_id 100
in the simulation file, there is user Bill Clinton (104) ... 
he is not a user_friend of mine  (he is listed as a friend for another user 165)
therefore, he should not be detected or be announced as a Nearby Friend.
This is odd because there are other users in the list - that do not announce, properly (Hillary Clinton)

**Comment by dakshatechnologies** [comment]
I  apologize for inconvenience  have done all the task in your app as per your requirement . Kindly have the task that you assign in M6 "if the word GLOBAL is placed after a BTID then the client should request the device/friend/trigger via REST from the server with a "Global" directive - that is - overriding the user (ownerID) of the record.  In other words - if GLOBAL, then the client retrieves and processes the device record (script etc) regardless of the userID matches."


you can set  the BTID as a global  in simulation file "XX:04:04:04:04:01 GLOBAL" Please check.

**Comment by cjcornell** [comment]
Thanks. This was a trivial one. thank you.  I will be closing out some of the milestones today I think.
