### ISSUE TITLE
Very Inconsistent Polling/Simulation

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#59]
This has been a persistent problem,  And one that has cost us hours and hours of testing (30-40 hours!).  It is intermittent but definition happens consistently... just cannot figure what causes it ...
but frequently, particularly after re-starting cyrano after an exit - Cyrano simply stops detecting nearby friends or devices.  It might have something to do with actual scanning of BTIDs (something that should not happen if a simulation file exists) - I suspect that BT scanning errors cause the simulation to suspend or skip any other reporting of nearby friends or triggers.

**Comment by dakshatechnologies** [comment]
can we discuss about this bug when you online so that i try let you know the solution

**Comment by cjcornell** [comment]
closing for now. I will document this again in more detail when I can test more fully
