### ISSUE TITLE
Issues with Polling Controls - Latest

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#60]
_Polling Parameter issues - not quite working as expected_:
- details_1_frequency   and  details_2_frequency  not working as expected (see below)
- announce_frquency - does not work as expected
- other issues see below.

_Test scenario 1_
Announce_frequency= 1	
details_1_frequency = 0
details_2_frequency = 1
result:  "There are 2 friends nearby" - Cyrano DOES NOT announce details_1 (personal_details)  - this is a bug!

_Test scenario 2_
Announce_frequency= 1	
details_1_frequency = 1
details_2_frequency = 0
seems to work properly by announcing about_text only

_Test scenario 1_
Announce_frequency= 1	
details_1_frequency = 1
details_2_frequency = 1
result:  NO ANNOUNCEMENTS at all ...BUG - this should announce both the about_text and persiinal_details for each new user.
I rebooted.
Then it worked!  -  this is a problem - see issue #59 

(other issues)
### FROM THE SPEC
- polling_interval   ####.#  seconds between scan/polls. (default=30.0 sec)
**(not represented in user_settings table - like, with all the OTHER polling parameters ... perhaps I omitted by mistake?  I wanted to change this,)**

- announce_frequency  ### - announce anything every ### polls (default= 1)
**what happens if this is =4?  announces only on every 4th poll?  does not seem to work**

 (CHANGED 06-04-2015) 
- details_1_frequency ### -
*** note this field is no longer a frequency.   
it is a value 0, 1, 2 ...
this parameter tells the client to announce the about_text for a NEWly detected friend (BTID is new, compared to the prior state list).  
** if =0 then does not announce.  if>0 announces. **
** (NOTE - the above does not work,   setting of 3 should still announce!)  **

 (CHANGED 06-04-2015) 
- details_2_frequency ### - (CHANGED 06-04-2015) 
*** note this field is no longer a frequency.   
it is a value 0, 1, 2 ...
this parameter tells the client to announce the personal_reminder for a NEWly detected friend (BTID is new, compared to the prior state list).  if =0 then does not announce.  if>0 announces.
** if =0 then does not announce.  if>0 announces. **
**(NOTE - the above does not work,   setting of 3 should still announce!)**
-----------------

**Comment by dakshatechnologies** [comment]
i am totally confused about this bug because  you already set the .
details_1_frequency = 0
details_2_frequency = 1
result: "There are 2 friends nearby" - Cyrano DOES NOT announce details_1 (personal_details) - this is a bug!
 you already set the value of details_1_frequency=0 then how it is possible Cyrano announce detail_1.
 help me to guide about this.

and same case already done in test 2

Test scenario 2
Announce_frequency= 1

details_1_frequency = 1
details_2_frequency = 0
seems to work properly by announcing about_text only

**Comment by cjcornell** [comment]
Yes, Rajesh - this is the problem - the polling and announcements are INCONSISTENT - and I have been trying to tell you this for quite some time.
I get different results for the same settings.
I have spend 15-20 hours (yes, hours) testing over the past 3 weeks and get inconsistent results
(similar to issue #59   )

**Comment by cjcornell** [comment]
I will close this issue for now - but polling is very inconsistent - not sure if due to problems with flags or with the scanning or something else
