### ISSUE TITLE
Bugs in Location Detect/Trigger

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#62]
There are 3 bugs in this report:
Testing one friend, and one location.

Setup:
Simulation file =
On
XX:01:01:01:01:01		// Steve Jobs

---
one location enabled
id=2 
33.6840972	-111.99038835	10200	demo	My Kitchen Table	This is my kitchen table, in Phoenix Arizona	52	2	1	This is my kitchen table, in Phoenix Arizona	hello cj

#### BEHAVIOR
1. Bug 1 - multiple location announcements
Sequence right now:
  a. Location announces ... but does not execute trigger
  b. Location announces again - and then triggers
  c. (the above is incorrect - there should be only 1 announcement, not 2)

2. Bug 2 - incorrect script triggering
  - behavior: Cyrano plays script commands for script_id=52, starting with 1,2,3,4,5 ....
  - this is incorrect (and we discussed this and corrected this in an earlier bug-report!)
  - Location "trigger" should execute  ONE script record  script_id=52, command_id=2
     - this is because BOTH are specified.
  - IF script_id-52 and command_id=blank  (in the location record) THEN the trigger should execute all commands for script_id=53
  - **important note** I think the above was implemented correctly for regular script triggers but not for scripts triggered by location

3. Bug 3 - location trigger keeps triggering
  - behavior - location trigger (in 2, above) is "fired" every polling loop.
  - this is incorrect
  - due to our polling rules/protocol, Cyrano should not announce or trigger the same location multiple times in a row.  (unless a parameter is set - which you have not implemented)
  - **important note** I think the above was implemented correctly for regular script triggers but not for scripts triggered by location

**Comment by dakshatechnologies** [comment]
Answer

1.the trigger can only execute after the announcement of  location name.And this is work correctly i have check this.

2.as per our conversation this task going assign me into the next milestone.

3. i have fix this you can check your new build
