### ISSUE TITLE
When script/trigger canceled - Announcements stop

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#64]
Behavior - 
1. when testing simulation file with a location-trigger, when the script that is triggered is canceled, then it appears that all other polling/announcements stop, forever.
2. when a device-trigger is executing, and the script is canceled, all polling/announcements stop, forever.

**Comment by dakshatechnologies** [comment]
i have  tested again the app and after cancel of trigger other announcements working fine

**Comment by cjcornell** [comment]
I can duplicate this every single time,

**Comment by cjcornell** [comment]
Duplicated it again - 
1. Location triggers a script. I tap 'cancel' during the script (to cancel the rest of the script from processing)
2. cyrano then apparently stops polling for friends or anything else. silent.

**Comment by dakshatechnologies** [comment]
issue resolved
