### ISSUE TITLE
Locations Should only Detect Announce when New

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#67]
See #62 

3. Bug 3 - location trigger keeps triggering
  - behavior - location trigger  is "fired" every polling loop.
  - this is incorrect
  - due to our polling rules/protocol, Cyrano should not announce or trigger the same location multiple times in a row.  (unless a parameter is set - which you have not implemented)
  - **important note** I think the above was implemented correctly for regular script triggers but not for scripts triggered by location

**Comment by dakshatechnologies** [comment]
i have fix this issue

**Comment by cjcornell** [comment]
is there a new build?  Or did you merely fix it for your own internal use?

**Comment by dakshatechnologies** [comment]
i have send you a new build please check

**Comment by cjcornell** [comment]
Will check
