### ISSUE TITLE
Friend Display Screen - Should play audio of friend personal_reminder

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#7]

**Comment by cjcornell** [comment]
This feature used to work, until recently ...
when I go to the Nearby Friend detail screen, the personal remindder should play

Also - the personal_reminder should play when the nearby friend is announced for the first time.

**Comment by dakshatechnologies** [comment]
this is work correctly please check

**Comment by cjcornell** [comment]
yes u are correct. I just did not get to closing this.
