### ISSUE TITLE
Mute/Snooze All - Icon Refresh

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#8]
When Mute-all/ Snooze all   (or UnMute/UnSnooze all) buttons are chosen on the Nearby Friends List - the list should be refeshed so that the mute/snooze icons are updates.

**Comment by kevinlee85** [comment]
Done.

**Comment by cjcornell** [comment]
Not done.

Icons do not display or refresh for Mute-All  or UnMute All  (there is a separate icon in the list for Mute)

See Issue #4     (where mute/snooze were explained in more detail).    It appears that internally, mute/snooze status are not being set after clicking Mute or Snooze.

@kevinlee85 
@dakshatechnologies
