### ISSUE TITLE
Cannot Log in with Cyrano_06_18_2015_08.apk Build!!

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#86]
I just tried to test the last build - to finally get back up to speed and get a baseline - and to see if the issues you fixed are OK.

But there is a critical issue. I can no longer log in with my userID and password.  I check the user table (just in case) ... and it is the same.

So that's that. i cannot log in.  Cannot test. cannot do anything.

**Comment by cjcornell** [comment]
I also tried earlier versions of the apk - same issue ... this implies that there was a change to the REST code that now makes it impossible to log in.  This is URGENT

**Comment by dakshatechnologies** [comment]
i have checked your mobile app web services is not working properly and this issue is not done from my side . The last time when i was send you build of your app every thing is working well including web services too .

**Comment by cjcornell** [comment]
well FYI only one other coder is working on Cyrano, and he has not touched anything in several weeks. And I looked at the github repo log and it looks like all the changes for the past few weeks have come from you're builds.  Regardless .. The project cannot move forward  until this is fixed.
