### ISSUE TITLE
Script commands appear not to advance or execute.

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#9]
Details
Script commands for each script (for instance the "BASELINE" script) .... each should 
1. display a screen for each command - 
2. screen should have on screen text, sometimes an image
3. screen should have buttons next/prev/cancel/pause ....
(the appearance of these buttons are dependent on the parameters for each script command.
4. the command text should also "play" Text to Speech
5. after a duration (>0) the command should auto advance to the next script command.

While this is assigned to @Atteq - @dakshatechnologies  and @avaiyakirtib   may know more about why this bug appeared in the first place.

**Comment by cjcornell** [comment]
This too seems to be working now.
@dakshatechnologies  
@Atteq 
@avaiyakirtib 

since I have not downloaded a new build - I assume the issue was REST related (and/or related to a setting in the database.

but I need to understand WHY this was not working earlier!

**Comment by cjcornell** [comment]
While this issue seems to be solved - I really want to know WHY it occurred.
whether it was due to old code re-appearing due to faulty merging, or due to some internal settings or anything else i was not aware of.

This is not about blame at all .. I just want understand why this bug occurred by surprise.

**Comment by Atteq** [comment]
might b because of REST Calls...!

**Comment by cjcornell** [comment]
well, that's a rather general answer.  The question is WHAT changed.  But this is OK @Atteq   I think @dakshatechnologies and @avaiyakirtib  are a little closer to the issue and can explain
